name: Update Version Registry

on:
  push:
    branches: 
      - main
    paths:
      - 'manifest.json'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout extension repository
        uses: actions/checkout@v4
        
      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: $VERSION"
          
      - name: Checkout version registry repository
        uses: actions/checkout@v4
        with:
          repository: rickoneeleven/extension-versions
          token: ${{ secrets.REGISTRY_PAT }}
          path: registry
          
      - name: Update versions.json
        run: |
          cd registry
          
          # Create versions.json if it doesn't exist
          if [ ! -f versions.json ]; then
            echo '{}' > versions.json
          fi
          
          # Update the version for this extension
          jq --arg version "${{ steps.get_version.outputs.VERSION }}" \
             '.["github-ai-context-builder"] = $version' \
             versions.json > versions.tmp.json
          
          mv versions.tmp.json versions.json
          
          # Display the updated content
          echo "Updated versions.json:"
          cat versions.json
          
      - name: Commit and push registry updates
        run: |
          cd registry
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add versions.json
          git commit -m "Update github-ai-context-builder to version ${{ steps.get_version.outputs.VERSION }}" || exit 0
          git push